### ISSUE TITLE
Device doesn't know about replicas in Rails 6 (multi-db mode)

### ISSUE THREAD

**Issue by alexander-alyoshin** [heartcombo/devise#5188]
##  Environment

- Ruby **[2.6.3]**
- Rails **[6.0.2.1]**
- Devise **[4.7.1]**

## Current behavior

```
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :validatable, :confirmable, :lockable,
         :timeoutable
```

```
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  connects_to database: { writing: :my_library, reading: :my_library_replica }
end
```

The problem is that Device tries to make an UPDATE without considering the replica.

```
gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:647:in `execute_and_clear': 
Write query attempted while in readonly mode: UPDATE "users" SET "confirmed_at" = $1, "updated_at" = $2 WHERE "users"."id" = $3 (ActiveRecord::ReadOnlyError)
    from gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:111:in `exec_delete'
    from gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:174:in `update'
    from gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/abstract/query_cache.rb:22:in `update'
    from gems/activerecord-6.0.2.1/lib/active_record/persistence.rb:385:in `_update_record'
    from gems/activerecord-6.0.2.1/lib/active_record/persistence.rb:897:in `_update_row'
    from gems/activerecord-6.0.2.1/lib/active_record/locking/optimistic.rb:79:in `_update_row'
    from gems/activerecord-6.0.2.1/lib/active_record/persistence.rb:919:in `_update_record'
    from gems/activerecord-6.0.2.1/lib/active_record/attribute_methods/dirty.rb:205:in `_update_record'
    from gems/activerecord-6.0.2.1/lib/active_record/callbacks.rb:336:in `block in _update_record'
    from gems/activesupport-6.0.2.1/lib/active_support/callbacks.rb:135:in `run_callbacks'
    from gems/bugsnag-6.13.0/lib/bugsnag/integrations/rails/active_record_rescue.rb:25:in `run_callbacks'
    from gems/activesupport-6.0.2.1/lib/active_support/callbacks.rb:827:in `_run_update_callbacks'
    from gems/activerecord-6.0.2.1/lib/active_record/callbacks.rb:336:in `_update_record'
    from gems/activerecord-6.0.2.1/lib/active_record/timestamp.rb:124:in `_update_record'
    from gems/activerecord-6.0.2.1/lib/active_record/persistence.rb:906:in `create_or_update'
    from gems/activerecord-6.0.2.1/lib/active_record/callbacks.rb:328:in `block in create_or_update'
    from gems/activesupport-6.0.2.1/lib/active_support/callbacks.rb:135:in `run_callbacks'
    from gems/bugsnag-6.13.0/lib/bugsnag/integrations/rails/active_record_rescue.rb:25:in `run_callbacks'
    from gems/activesupport-6.0.2.1/lib/active_support/callbacks.rb:827:in `_run_save_callbacks'
    from gems/activerecord-6.0.2.1/lib/active_record/callbacks.rb:328:in `create_or_update'
    from gems/activerecord-6.0.2.1/lib/active_record/timestamp.rb:129:in `create_or_update'
    from gems/activerecord-6.0.2.1/lib/active_record/persistence.rb:470:in `save'
    from gems/activerecord-6.0.2.1/lib/active_record/validations.rb:47:in `save'
    from gems/activerecord-6.0.2.1/lib/active_record/transactions.rb:315:in `block in save'
    from gems/activerecord-6.0.2.1/lib/active_record/transactions.rb:375:in `block in with_transaction_returning_status'
    from gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:281:in `block in transaction'
    from gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:280:in `block in within_new_transaction'
    from /home/alyoshin/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
    from gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:278:in `within_new_transaction'
    from gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:281:in `transaction'
    from gems/activerecord-6.0.2.1/lib/active_record/transactions.rb:212:in `transaction'
    from gems/activerecord-6.0.2.1/lib/active_record/transactions.rb:366:in `with_transaction_returning_status'
    from gems/activerecord-6.0.2.1/lib/active_record/transactions.rb:315:in `save'
    from gems/activerecord-6.0.2.1/lib/active_record/suppressor.rb:44:in `save'
    from gems/devise-4.7.1/lib/devise/models/confirmable.rb:97:in `block in confirm'
    from gems/devise-4.7.1/lib/devise/models/confirmable.rb:239:in `pending_any_confirmation'
    from gems/devise-4.7.1/lib/devise/models/confirmable.rb:80:in `confirm'
    from gems/devise-4.7.1/lib/devise/models/confirmable.rb:373:in `confirm_by_token'
    from gems/devise-4.7.1/app/controllers/devise/confirmations_controller.rb:23:in `show'
    from gems/actionpack-6.0.2.1/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
    from gems/actionpack-6.0.2.1/lib/abstract_controller/base.rb:196:in `process_action'
    from gems/ddtrace-0.32.0/lib/ddtrace/contrib/action_pack/action_controller/instrumentation.rb:114:in `process_action'
    from gems/actionpack-6.0.2.1/lib/action_controller/metal/rendering.rb:30:in `process_action'
    from gems/actionpack-6.0.2.1/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
    from gems/activesupport-6.0.2.1/lib/active_support/callbacks.rb:135:in `run_callbacks'
    from gems/actionpack-6.0.2.1/lib/abstract_controller/callbacks.rb:41:in `process_action'
    from gems/actionpack-6.0.2.1/lib/action_controller/metal/rescue.rb:22:in `process_action'
    from gems/actionpack-6.0.2.1/lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
    from gems/activesupport-6.0.2.1/lib/active_support/notifications.rb:180:in `block in instrument'
    from gems/activesupport-6.0.2.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    from gems/activesupport-6.0.2.1/lib/active_support/notifications.rb:180:in `instrument'
    from gems/actionpack-6.0.2.1/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
    from gems/actionpack-6.0.2.1/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
    from gems/activerecord-6.0.2.1/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
    from gems/actionpack-6.0.2.1/lib/abstract_controller/base.rb:136:in `process'
    from gems/actionview-6.0.2.1/lib/action_view/rendering.rb:39:in `process'
    from gems/actionpack-6.0.2.1/lib/action_controller/metal.rb:191:in `dispatch'
    from gems/actionpack-6.0.2.1/lib/action_controller/metal.rb:252:in `dispatch'
    from gems/actionpack-6.0.2.1/lib/action_dispatch/routing/route_set.rb:51:in `dispatch'
    from gems/actionpack-6.0.2.1/lib/action_dispatch/routing/route_set.rb:33:in `serve'
    from gems/actionpack-6.0.2.1/lib/action_dispatch/routing/mapper.rb:18:in `block in <class:Constraints>'
    from gems/actionpack-6.0.2.1/lib/action_dispatch/routing/mapper.rb:48:in `serve'
    from gems/actionpack-6.0.2.1/lib/action_dispatch/journey/router.rb:49:in `block in serve'
    from gems/actionpack-6.0.2.1/lib/action_dispatch/journey/router.rb:32:in `each'
    from gems/actionpack-6.0.2.1/lib/action_dispatch/journey/router.rb:32:in `serve'
    from gems/actionpack-6.0.2.1/lib/action_dispatch/routing/route_set.rb:837:in `call'
    from gems/rack-affiliates-0.4.0/lib/rack-affiliates.rb:50:in `call'
    from gems/activerecord-6.0.2.1/lib/active_record/middleware/database_selector.rb:53:in `block in call'
    from gems/activerecord-6.0.2.1/lib/active_record/middleware/database_selector/resolver.rb:59:in `block (2 levels) in read_from_replica'
    from gems/activesupport-6.0.2.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    from gems/activerecord-6.0.2.1/lib/active_record/middleware/database_selector/resolver.rb:58:in `block in read_from_replica'
    from gems/activerecord-6.0.2.1/lib/active_record/connection_handling.rb:269:in `swap_connection_handler'
    from gems/activerecord-6.0.2.1/lib/active_record/connection_handling.rb:176:in `with_handler'
    from gems/activerecord-6.0.2.1/lib/active_record/connection_handling.rb:139:in `connected_to'
    from gems/activerecord-6.0.2.1/lib/active_record/middleware/database_selector/resolver.rb:57:in `read_from_replica'
    from gems/activerecord-6.0.2.1/lib/active_record/middleware/database_selector/resolver.rb:38:in `read'
    from gems/activerecord-6.0.2.1/lib/active_record/middleware/database_selector.rb:64:in `select_database'
    from gems/activerecord-6.0.2.1/lib/active_record/middleware/database_selector.rb:52:in `call'
    from gems/warden-1.2.8/lib/warden/manager.rb:36:in `block in call'
    from gems/warden-1.2.8/lib/warden/manager.rb:34:in `catch'
    from gems/warden-1.2.8/lib/warden/manager.rb:34:in `call'
    from gems/rack-2.1.2/lib/rack/tempfile_reaper.rb:17:in `call'
    from gems/rack-2.1.2/lib/rack/etag.rb:27:in `call'
    from gems/rack-2.1.2/lib/rack/conditional_get.rb:27:in `call'
    from gems/rack-2.1.2/lib/rack/head.rb:14:in `call'
    from gems/actionpack-6.0.2.1/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
    from gems/rack-2.1.2/lib/rack/session/abstract/id.rb:269:in `context'
    from gems/rack-2.1.2/lib/rack/session/abstract/id.rb:263:in `call'
    from gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/cookies.rb:648:in `call'
    from gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
    from gems/activesupport-6.0.2.1/lib/active_support/callbacks.rb:101:in `run_callbacks'
    from gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
    from gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
    from gems/bugsnag-6.13.0/lib/bugsnag/integrations/rack.rb:49:in `call'
    from gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
    from gems/ddtrace-0.32.0/lib/ddtrace/contrib/rails/middlewares.rb:17:in `call'
    from gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
    from gems/railties-6.0.2.1/lib/rails/rack/logger.rb:38:in `call_app'
    from gems/railties-6.0.2.1/lib/rails/rack/logger.rb:26:in `block in call'
    from gems/activesupport-6.0.2.1/lib/active_support/tagged_logging.rb:80:in `block in tagged'
    from gems/activesupport-6.0.2.1/lib/active_support/tagged_logging.rb:28:in `tagged'
    from gems/activesupport-6.0.2.1/lib/active_support/tagged_logging.rb:80:in `tagged'
    from gems/railties-6.0.2.1/lib/rails/rack/logger.rb:26:in `call'
    from gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
    from gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'
    from gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/request_id.rb:27:in `call'
    from gems/rack-2.1.2/lib/rack/method_override.rb:24:in `call'
    from gems/rack-2.1.2/lib/rack/runtime.rb:24:in `call'
    from gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
    from gems/rack-cache-1.11.0/lib/rack/cache/context.rb:141:in `forward'
    from gems/rack-cache-1.11.0/lib/rack/cache/context.rb:250:in `fetch'
    from gems/rack-cache-1.11.0/lib/rack/cache/context.rb:190:in `lookup'
    from gems/rack-cache-1.11.0/lib/rack/cache/context.rb:67:in `call!'
    from gems/rack-cache-1.11.0/lib/rack/cache/context.rb:52:in `call'
    from gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/static.rb:126:in `call'
    from gems/rack-2.1.2/lib/rack/sendfile.rb:113:in `call'
    from gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/ssl.rb:74:in `call'
    from gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/host_authorization.rb:77:in `call'
    from gems/rack-utf8_sanitizer-1.6.0/lib/rack/utf8_sanitizer.rb:22:in `call'
    from gems/ddtrace-0.32.0/lib/ddtrace/contrib/rack/middlewares.rb:85:in `call'
    from gems/railties-6.0.2.1/lib/rails/engine.rb:526:in `call'
    from gems/rack-2.1.2/lib/rack/tempfile_reaper.rb:17:in `call'
    from gems/rack-2.1.2/lib/rack/lint.rb:51:in `_call'
    from gems/rack-2.1.2/lib/rack/lint.rb:39:in `call'
    from gems/rack-2.1.2/lib/rack/show_exceptions.rb:25:in `call'
    from gems/rack-2.1.2/lib/rack/common_logger.rb:35:in `call'
    from gems/rack-2.1.2/lib/rack/chunked.rb:73:in `call'
    from gems/rack-2.1.2/lib/rack/content_length.rb:17:in `call'
    from gems/unicorn-5.5.3/lib/unicorn/http_server.rb:605:in `process_client'
    from gems/unicorn-5.5.3/lib/unicorn/http_server.rb:700:in `worker_loop'
    from gems/unicorn-5.5.3/lib/unicorn/http_server.rb:548:in `spawn_missing_workers'
    from gems/unicorn-5.5.3/lib/unicorn/http_server.rb:144:in `start'
    from gems/unicorn-5.5.3/bin/unicorn:128:in `<top (required)>'
    from bin/unicorn:23:in `load'
    from bin/unicorn:23:in `<main>'
    from bin/ruby_executable_hooks:24:in `eval'
    from bin/ruby_executable_hooks:24:in `<main>'
```

**Comment by giedriusr** [comment]
Not sure if you've seen, but some discussion happened here: https://github.com/heartcombo/devise/issues/5133

**Comment by rafaelfranca** [comment]
Thank you for the issue. I agree with this comment https://github.com/heartcombo/devise/issues/5133#issuecomment-534180424. I don't think devise should deal with those cases. If anything, what is broken is the connection switching middleware selecting read only connections for `GET` requests. I think applications will have to deal with those cases either changing the middleware or by doing what was suggested in the linked comment.
