### ISSUE TITLE
devise_for in routes.rb breaks assets:precompile on production

### ISSUE THREAD

**Issue by hsyntnc** [heartcombo/devise#5231]
## Environment

- Ruby 2.7.0
- Rails 6.0.2.2
- Devise 4.7.1

## Current behavior
If i use devise_for helper on my routes.rb, it's trying to initialize a user object and breaks the pipeline when building an image from Dockerfile. It says DATABASE_NAME is missing but i set my environment variables (db name, db host etc.) when running the container not when building it. 

It's giving an error like;
````
Caused by:
KeyError: key not found: "DATABASE_NAME"
(erb):26:in `fetch'
(erb):26:in `<main>'
/usr/local/bundle/gems/railties-6.0.2.2/lib/rails/application/configuration.rb:228:in `database_configuration'
/usr/local/bundle/gems/activerecord-6.0.2.2/lib/active_record/railtie.rb:200:in `block (2 levels) in <class:Railtie>'
/usr/local/bundle/gems/activesupport-6.0.2.2/lib/active_support/lazy_load_hooks.rb:72:in `class_eval'
/usr/local/bundle/gems/activesupport-6.0.2.2/lib/active_support/lazy_load_hooks.rb:72:in `block in execute_hook'
/usr/local/bundle/gems/activesupport-6.0.2.2/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
/usr/local/bundle/gems/activesupport-6.0.2.2/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
/usr/local/bundle/gems/activesupport-6.0.2.2/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
/usr/local/bundle/gems/activesupport-6.0.2.2/lib/active_support/lazy_load_hooks.rb:51:in `each'
/usr/local/bundle/gems/activesupport-6.0.2.2/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
/usr/local/bundle/gems/activerecord-6.0.2.2/lib/active_record/base.rb:327:in `<module:ActiveRecord>'
/usr/local/bundle/gems/activerecord-6.0.2.2/lib/active_record/base.rb:27:in `<main>'
/usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/usr/local/bundle/gems/zeitwerk-2.3.0/lib/zeitwerk/kernel.rb:23:in `require'
/myapp/app/models/application_record.rb:1:in `<main>'
/usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/usr/local/bundle/gems/zeitwerk-2.3.0/lib/zeitwerk/kernel.rb:16:in `require'
/myapp/app/models/user.rb:1:in `<main>'
/usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/usr/local/bundle/gems/zeitwerk-2.3.0/lib/zeitwerk/kernel.rb:16:in `require'
/usr/local/bundle/gems/activesupport-6.0.2.2/lib/active_support/inflector/methods.rb:282:in `const_get'
/usr/local/bundle/gems/activesupport-6.0.2.2/lib/active_support/inflector/methods.rb:282:in `block in constantize'
/usr/local/bundle/gems/activesupport-6.0.2.2/lib/active_support/inflector/methods.rb:280:in `each'
/usr/local/bundle/gems/activesupport-6.0.2.2/lib/active_support/inflector/methods.rb:280:in `inject'
/usr/local/bundle/gems/activesupport-6.0.2.2/lib/active_support/inflector/methods.rb:280:in `constantize'
/usr/local/bundle/gems/activesupport-6.0.2.2/lib/active_support/dependencies/zeitwerk_integration.rb:19:in `constantize'
/usr/local/bundle/gems/devise-4.7.1/lib/devise.rb:320:in `get'
/usr/local/bundle/gems/devise-4.7.1/lib/devise/mapping.rb:83:in `to'
/usr/local/bundle/gems/devise-4.7.1/lib/devise/mapping.rb:78:in `modules'
/usr/local/bundle/gems/devise-4.7.1/lib/devise/mapping.rb:95:in `routes'
/usr/local/bundle/gems/devise-4.7.1/lib/devise/mapping.rb:162:in `default_used_route'
/usr/local/bundle/gems/devise-4.7.1/lib/devise/mapping.rb:72:in `initialize'
/usr/local/bundle/gems/devise-4.7.1/lib/devise.rb:350:in `new'
/usr/local/bundle/gems/devise-4.7.1/lib/devise.rb:350:in `add_mapping'
/usr/local/bundle/gems/devise-4.7.1/lib/devise/rails/routes.rb:243:in `block in devise_for'
/usr/local/bundle/gems/devise-4.7.1/lib/devise/rails/routes.rb:242:in `each'
/usr/local/bundle/gems/devise-4.7.1/lib/devise/rails/routes.rb:242:in `devise_for'
/myapp/config/routes.rb:10:in `block in <main>'
/usr/local/bundle/gems/actionpack-6.0.2.2/lib/action_dispatch/routing/route_set.rb:429:in `instance_exec'
/usr/local/bundle/gems/actionpack-6.0.2.2/lib/action_dispatch/routing/route_set.rb:429:in `eval_block'
/usr/local/bundle/gems/actionpack-6.0.2.2/lib/action_dispatch/routing/route_set.rb:411:in `draw'
/myapp/config/routes.rb:3:in `<main>'
/usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
/usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
/usr/local/bundle/gems/railties-6.0.2.2/lib/rails/application/routes_reloader.rb:41:in `block in load_paths'
/usr/local/bundle/gems/railties-6.0.2.2/lib/rails/application/routes_reloader.rb:41:in `each'
/usr/local/bundle/gems/railties-6.0.2.2/lib/rails/application/routes_reloader.rb:41:in `load_paths'
/usr/local/bundle/gems/railties-6.0.2.2/lib/rails/application/routes_reloader.rb:20:in `reload!'
/usr/local/bundle/gems/railties-6.0.2.2/lib/rails/application/routes_reloader.rb:30:in `block in updater'
/usr/local/bundle/gems/activesupport-6.0.2.2/lib/active_support/file_update_checker.rb:83:in `execute'
/usr/local/bundle/gems/railties-6.0.2.2/lib/rails/application/routes_reloader.rb:10:in `execute'
/usr/local/bundle/gems/railties-6.0.2.2/lib/rails/application/finisher.rb:184:in `block in <module:Finisher>'
/usr/local/bundle/gems/railties-6.0.2.2/lib/rails/initializable.rb:32:in `instance_exec'
/usr/local/bundle/gems/railties-6.0.2.2/lib/rails/initializable.rb:32:in `run'
/usr/local/bundle/gems/railties-6.0.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/local/bundle/gems/railties-6.0.2.2/lib/rails/initializable.rb:60:in `run_initializers'
/usr/local/bundle/gems/railties-6.0.2.2/lib/rails/application.rb:363:in `initialize!'
/myapp/config/environment.rb:5:in `<main>'
/usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/usr/local/bundle/gems/zeitwerk-2.3.0/lib/zeitwerk/kernel.rb:23:in `require'
/usr/local/bundle/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:325:in `block in require'
/usr/local/bundle/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:291:in `load_dependency'
/usr/local/bundle/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:325:in `require'
/usr/local/bundle/gems/railties-6.0.2.2/lib/rails/application.rb:339:in `require_environment!'
/usr/local/bundle/gems/railties-6.0.2.2/lib/rails/application.rb:515:in `block in run_tasks_blocks'
/usr/local/bundle/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:62:in `block (2 levels) in define'
/usr/local/bundle/gems/railties-6.0.2.2/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/usr/local/bundle/gems/railties-6.0.2.2/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/usr/local/bundle/gems/railties-6.0.2.2/lib/rails/command.rb:48:in `invoke'
/usr/local/bundle/gems/railties-6.0.2.2/lib/rails/commands.rb:18:in `<main>'
/usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/usr/local/bundle/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:325:in `block in require'
/usr/local/bundle/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:291:in `load_dependency'
/usr/local/bundle/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:325:in `require'
bin/rails:9:in `<main>'
Tasks: TOP => environment
(See full trace by running task with --trace)
````

Dockerfile;
````
FROM ruby:2.7.0
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update -qq && apt-get install -y build-essential nodejs yarn
COPY . /myapp/
COPY Gemfile* /myapp/
WORKDIR /myapp
RUN bundle install --without development test
RUN yarn install --check-files
RUN RAILS_ENV=production bundle exec rails assets:precompile
````

Devise routes on my routes.rb;
````
  # Devise Routes
  devise_for :users,
             controllers: {
                 sessions: 'sessions',
                 registrations: 'registrations',
                 passwords: 'passwords' },
             path: '/',
             path_names: { sign_in: 'login',
                           sign_up: 'new',
                           sign_out: 'logout',
                           password: 'secret',
                           confirmation: 'verification' }
````
## Expected behavior
It shouldn't initialize user object and continue precompiling assets.

**Comment by rafaelfranca** [comment]
If your app depends in a environment variable to run you need to also set it when compiling the assets since compiling the assets also run the app.

**Comment by hsyntnc** [comment]
but it doesn't run the app and compile assets perfectly if i remove devise_for line from my routes.rb

**Comment by hsyntnc** [comment]
it only depends on secret_key_base but i store it in credentials so it shouldn't need any other environment variable to precompile assets.

**Comment by rafaelfranca** [comment]
The entire application is loaded when precompiling assets and the Rails boot will try to evaluate the connection configuration. This is not related to devise.

**Comment by hsyntnc** [comment]
Thanks, I'm setting all the environment variables on build now and it seems ok. 
I thought it's related with devise just because it was failing when i use devise_for helper in routes.rb

**Comment by rafaelfranca** [comment]
That was the first reference to the database connection configuration, but in production, since code is eager loaded, as soon the first model is loaded you would see the same error, and since assets compilation loads the app, and you were asking to load in the production environment, that would also happen.

**Comment by fagiani** [comment]
For others facing similar issues, as in my case I do not require the application to load the database in order to run this rake task, I was able to work around it for precompiling assets by surrounding `devise_for` and `devise_scope` with the following code:

    unless defined?(::Rake::SprocketsTask)
      #...
    end

I hope it may become useful to others in the future!

**Comment by thedarkside** [comment]
@fagiani stumbled upon this recently. First i planned to follow your suggestion but because it felt not right (i mean, why should the router be aware of the SprocketsTask, right?) i inspected the app further. 

In my case the reason was a bad design decision which led to a database hit in the moment the model got loaded. As soon as i refactored this, the assets:precompile task runs without PG exception again.
