### ISSUE TITLE
Error in setup when trying to run rails generate

### ISSUE THREAD

**Issue by beshur** [heartcombo/devise#5277]
## Environment

- Ruby **2.6.3p62**
- Rails **6.0.3**
- Devise **4.7.1**

## Current behavior

When running up the server everything is okay
`RAILS_MASTER_KEY=$XX_MASTER_KEY RAILS_ENV=development rails s` 

When running the generate command, I get the error:

```
RAILS_MASTER_KEY=$XX_MASTER_KEY RAILS_ENV=development rails generate migration
/Users/shu/work/project/config/initializers/devise.rb:21:in `block in <main>': undefined method `[]' for nil:NilClass (NoMethodError)
	from /Users/shu/gems/gems/devise-4.7.1/lib/devise.rb:311:in `setup'
	from /Users/shu/work/project/config/initializers/devise.rb:5:in `<main>'
```

## Expected behavior

Generate runs smoothly.

**Comment by beshur** [comment]
Well, the issue went away after some magical moves, like sourcing .bash_profile and running `rvm reset`
