### ISSUE TITLE
Rails 7 support — installer crashes against 7.0.0.alpha2

### ISSUE THREAD

**Issue by jasonfb** [heartcombo/devise#5408]
## Pre-check

when devise is installed with rails **7.0.0.alpha2**, the devise installer crashes with 

```
## Environment

- Ruby **2.7.2**
- Rails **7.0.0.alpha**
- Devise **4.8.0**

## Current behavior

after add `gem 'devise'`, the installer crashes with

```
% rails generate devise:install
Resolving dependencies...
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
Traceback (most recent call last):
	36: from bin/rails:4:in `<main>'
	35: from /Users/jason/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	34: from /Users/jason/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	33: from /Users/jason/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	32: from /Users/jason/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	31: from /Users/jason/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	30: from /Users/jason/.rvm/gems/ruby-2.7.2/gems/railties-7.0.0.alpha2/lib/rails/commands.rb:18:in `<main>'
	29: from /Users/jason/.rvm/gems/ruby-2.7.2/gems/railties-7.0.0.alpha2/lib/rails/command.rb:48:in `invoke'
	28: from /Users/jason/.rvm/gems/ruby-2.7.2/gems/railties-7.0.0.alpha2/lib/rails/command/base.rb:87:in `perform'
	27: from /Users/jason/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	26: from /Users/jason/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	25: from /Users/jason/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	24: from /Users/jason/.rvm/gems/ruby-2.7.2/gems/railties-7.0.0.alpha2/lib/rails/commands/generate/generate_command.rb:21:in `perform'
	23: from /Users/jason/.rvm/gems/ruby-2.7.2/gems/railties-7.0.0.alpha2/lib/rails/command/actions.rb:14:in `require_application_and_environment!'
	22: from /Users/jason/.rvm/gems/ruby-2.7.2/gems/railties-7.0.0.alpha2/lib/rails/command/actions.rb:22:in `require_application!'
	21: from /Users/jason/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	20: from /Users/jason/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	19: from /Users/jason/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	18: from /Users/jason/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	17: from /Users/jason/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	16: from /Users/jason/Work/Hot_Glue/DevTest-20211010-Rail7/config/application.rb:7:in `<main>'
	15: from /Users/jason/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/bundler.rb:174:in `require'
	14: from /Users/jason/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/bundler/runtime.rb:58:in `require'
	13: from /Users/jason/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/bundler/runtime.rb:58:in `each'
	12: from /Users/jason/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/bundler/runtime.rb:69:in `block in require'
	11: from /Users/jason/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/bundler/runtime.rb:69:in `each'
	10: from /Users/jason/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/bundler/runtime.rb:74:in `block (2 levels) in require'
	 9: from /Users/jason/.rvm/gems/ruby-2.7.2/gems/zeitwerk-2.5.0.beta5/lib/zeitwerk/kernel.rb:35:in `require'
	 8: from /Users/jason/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	 7: from /Users/jason/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	 6: from /Users/jason/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	 5: from /Users/jason/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	 4: from /Users/jason/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	 3: from /Users/jason/.rvm/gems/ruby-2.7.2/gems/devise-4.8.0/lib/devise.rb:11:in `<main>'
	 2: from /Users/jason/.rvm/gems/ruby-2.7.2/gems/devise-4.8.0/lib/devise.rb:342:in `<module:Devise>'
	 1: from /Users/jason/.rvm/gems/ruby-2.7.2/gems/devise-4.8.0/lib/devise.rb:340:in `mailer='
/Users/jason/.rvm/gems/ruby-2.7.2/gems/devise-4.8.0/lib/devise.rb:321:in `ref': undefined method `reference' for ActiveSupport::Dependencies:Module (NoMethodError)

```

## Expected behavior

• this version appears to be incompatible with Rails 7

**Comment by lxxxvi** [comment]
So I guess we can use this until Rails 7 is final:

```ruby
gem "devise", git: "https://github.com/heartcombo/devise.git", branch: "main"
```
