### ISSUE TITLE
reference' for ActiveSupport::Dependencies:Module (NoMethodError) on rails 7.0.0-rc1

### ISSUE THREAD

**Issue by MdreW** [heartcombo/devise#5428]
## Environment

- Ruby **3.0.3**
- Rails **7.0.0-rc1**
- Devise **4.8.0**

## Current behavior

On testing a new installation of rails 7.0.0-rc1, if devise gem is added every command have the seguent error:

```
rails c
/home/andrea/.rvm/gems/ruby-3.0.3@landing/gems/devise-4.8.0/lib/devise.rb:321:in `ref': undefined method `reference' for ActiveSupport::Dependencies:Module (NoMethodError)
        from /home/andrea/.rvm/gems/ruby-3.0.3@landing/gems/devise-4.8.0/lib/devise.rb:340:in `mailer='
        from /home/andrea/.rvm/gems/ruby-3.0.3@landing/gems/devise-4.8.0/lib/devise.rb:342:in `<module:Devise>'
        from /home/andrea/.rvm/gems/ruby-3.0.3@landing/gems/devise-4.8.0/lib/devise.rb:11:in `<main>'
        from /home/andrea/.rvm/gems/ruby-3.0.3@landing/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        from /home/andrea/.rvm/gems/ruby-3.0.3@landing/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        from /home/andrea/.rvm/gems/ruby-3.0.3@landing/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:100:in `register'
        from /home/andrea/.rvm/gems/ruby-3.0.3@landing/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        from /home/andrea/.rvm/gems/ruby-3.0.3@landing/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        from /home/andrea/.rvm/gems/ruby-3.0.3@landing/gems/zeitwerk-2.5.1/lib/zeitwerk/kernel.rb:35:in `require'
        from /home/andrea/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/bundler/runtime.rb:60:in `block (2 levels) in require'
        from /home/andrea/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/bundler/runtime.rb:55:in `each'
        from /home/andrea/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/bundler/runtime.rb:55:in `block in require'
        from /home/andrea/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/bundler/runtime.rb:44:in `each'
        from /home/andrea/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/bundler/runtime.rb:44:in `require'
        from /home/andrea/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/bundler.rb:175:in `require'
        from /home/andrea/Project/ISPRA/landing/config/application.rb:7:in `<main>'
        from /home/andrea/.rvm/gems/ruby-3.0.3@landing/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        from /home/andrea/.rvm/gems/ruby-3.0.3@landing/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        from /home/andrea/.rvm/gems/ruby-3.0.3@landing/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:100:in `register'
        from /home/andrea/.rvm/gems/ruby-3.0.3@landing/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        from /home/andrea/.rvm/gems/ruby-3.0.3@landing/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        from /home/andrea/.rvm/gems/ruby-3.0.3@landing/gems/railties-7.0.0.rc1/lib/rails/command/actions.rb:22:in `require_application!'
        from /home/andrea/.rvm/gems/ruby-3.0.3@landing/gems/railties-7.0.0.rc1/lib/rails/command/actions.rb:14:in `require_application_and_environment!'
        from /home/andrea/.rvm/gems/ruby-3.0.3@landing/gems/railties-7.0.0.rc1/lib/rails/commands/console/console_command.rb:101:in `perform'
        from /home/andrea/.rvm/gems/ruby-3.0.3@landing/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
        from /home/andrea/.rvm/gems/ruby-3.0.3@landing/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
        from /home/andrea/.rvm/gems/ruby-3.0.3@landing/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
        from /home/andrea/.rvm/gems/ruby-3.0.3@landing/gems/railties-7.0.0.rc1/lib/rails/command/base.rb:87:in `perform'
        from /home/andrea/.rvm/gems/ruby-3.0.3@landing/gems/railties-7.0.0.rc1/lib/rails/command.rb:48:in `invoke'
        from /home/andrea/.rvm/gems/ruby-3.0.3@landing/gems/railties-7.0.0.rc1/lib/rails/commands.rb:18:in `<main>'
        from /home/andrea/.rvm/gems/ruby-3.0.3@landing/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        from /home/andrea/.rvm/gems/ruby-3.0.3@landing/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        from /home/andrea/.rvm/gems/ruby-3.0.3@landing/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:100:in `register'
        from /home/andrea/.rvm/gems/ruby-3.0.3@landing/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        from /home/andrea/.rvm/gems/ruby-3.0.3@landing/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        from bin/rails:4:in `<main>'
```

If I remove devise gem all work fine

**Comment by MdreW** [comment]
Hi @carlosantoniodasilva , with master branch work fine, Many thanks!
