### ISSUE TITLE
Devise throwing "Devise could not find the `Warden::Proxy`environement" in production application"

### ISSUE THREAD

**Issue by kvish** [heartcombo/devise#5437]
## Environment

- Ruby: 2.6.5
- Rails: 6.0.2
- Devise: 4.2

## Current behavior

On our production application running in Heroku we began to see Devise errors on most API requests. We solved this problem by restarting our heroku instance and we have not seen this issue again. I have noticed a similar issue: https://github.com/heartcombo/devise/issues/4346, but I dont think this is the same case. 

API error
```
 [06065af4-6792-4758-92fd-62714bfade8e] {"method":"POST","path":"/500","format":"*/*","controller":"ErrorsController","action":"internal_server_error","status":500,"error":"Devise::MissingWarden: Devise could not find the `Warden::Proxy` instance on your request environment.\nMake sure that your application is loading Devise and Warden as expected and that the `Warden::Manager` middleware is present in your middleware stack.\nIf you are seeing this on one of your tests, ensure that your tests are either executing the Rails middleware stack or that your tests are using the `Devise::Test::ControllerHelpers` module to inject the `request.env['warden']` object for you.","duration":1.28,"view":0.0,"db":0.0,"params":{"operationName":"getPoliciesForCompanyUser","variables":{"companyId":"d874290a-13b3-488b-a086-891600b94268","companyUserId":"994fd68b-7bd0-437a-a0b1-37821d0dc76c","current_company_user_id":"994fd68b-7bd0-437a-a0b1-37821d0dc76c"},"query":"query getPoliciesForCompanyUser($companyId: ID!, $companyUserId: ID!) {\n  getPoliciesForCompanyUser(companyId: $companyId, companyUserId: $companyUserId) {\n    collection {\n      ...PolicyType\n      companyUserPolicy(companyUserId: $companyUserId) {\n        id\n        acceptedAt\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n}\n\nfragment PolicyType on Policy {\n  id\n  name\n  content\n  interpolatedContent\n  status\n  publishedAt\n  updatedAt\n  optionValues\n  tokenValues\n  parentPolicyId\n  addendumCount\n  owner {\n    id\n    name\n    imageUrl\n    __typename\n  }\n  __typename\n}\n","controller":"errors","action":"internal_server_error","error":{"operationName":"getPoliciesForCompanyUser","variables":{"companyId":"d874290a-13b3-488b-a086-891600b94268","companyUserId":"994fd68b-7bd0-437a-a0b1-37821d0dc76c","current_company_user_id":"994fd68b-7bd0-437a-a0b1-37821d0dc76c"},"query":"query getPoliciesForCompanyUser($companyId: ID!, $companyUserId: ID!) {\n  getPoliciesForCompanyUser(companyId: $companyId, companyUserId: $companyUserId) {\n    collection {\n      ...PolicyType\n      companyUserPolicy(companyUserId: $companyUserId) {\n        id\n        acceptedAt\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n}\n\nfragment PolicyType on Policy {\n  id\n  name\n  content\n  interpolatedContent\n  status\n  publishedAt\n  updatedAt\n  optionValues\n  tokenValues\n  parentPolicyId\n  addendumCount\n  owner {\n    id\n    name\n    imageUrl\n    __typename\n  }\n  __typename\n}\n"}},"level":"ERROR"}
 
 ```
 
 Stack trace:
 
 ```
 Error during failsafe response: Devise could not find the `Warden::Proxy` instance on your request environment.
 Dec 13 09:15:23 secureframe app/web.1 Make sure that your application is loading Devise and Warden as expected and that the `Warden::Manager` middleware is present in your middleware stack.
 Dec 13 09:15:23 secureframe app/web.1 If you are seeing this on one of your tests, ensure that your tests are either executing the Rails middleware stack or that your tests are using the `Devise::Test::ControllerHelpers` module to inject the `request.env['warden']` object for you.
 Dec 13 09:15:23 secureframe app/web.1   /app/vendor/bundle/ruby/2.6.0/gems/devise-4.7.2/lib/devise/controllers/helpers.rb:143:in `warden'
 Dec 13 09:15:23 secureframe app/web.1   /app/vendor/bundle/ruby/2.6.0/gems/devise-4.7.2/lib/devise/controllers/sign_in_out.rb:96:in `block in sign_out_all_scopes'
 Dec 13 09:15:23 secureframe app/web.1   /app/vendor/bundle/ruby/2.6.0/gems/devise-4.7.2/lib/devise/controllers/sign_in_out.rb:96:in `map'
 Dec 13 09:15:23 secureframe app/web.1   /app/vendor/bundle/ruby/2.6.0/gems/devise-4.7.2/lib/devise/controllers/sign_in_out.rb:96:in `sign_out_all_scopes'
 Dec 13 09:15:23 secureframe app/web.1   /app/vendor/bundle/ruby/2.6.0/gems/devise-4.7.2/lib/devise/controllers/helpers.rb:257:in `handle_unverified_request'
 Dec 13 09:15:23 secureframe app/web.1   /app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.2/lib/action_controller/metal/request_forgery_protection.rb:242:in `verify_authenticity_token'
 Dec 13 09:15:23 secureframe app/web.1   /app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:428:in `block in make_lambda'
 Dec 13 09:15:23 secureframe app/web.1   /app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:200:in `block (2 levels) in halting'
 Dec 13 09:15:23 secureframe app/web.1   /app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.2/lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
 Dec 13 09:15:23 secureframe app/web.1   /app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:201:in `block in halting'
 Dec 13 09:15:23 secureframe app/web.1   /app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:513:in `block in invoke_before'
 Dec 13 09:15:23 secureframe app/web.1   /app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:513:in `each'
 Dec 13 09:15:23 secureframe app/web.1   /app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:513:in `invoke_before'
 Dec 13 09:15:23 secureframe app/web.1   /app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:110:in `block in run_callbacks'
 Dec 13 09:15:23 secureframe app/web.1   /app/vendor/bundle/ruby/2.6.0/gems/audited-4.9.0/lib/audited/sweeper.rb:14:in `around'
 Dec 13 09:15:23 secureframe app/web.1   /app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
 Dec 13 09:15:23 secureframe app/web.1   /app/vendor/bundle/ruby/2.6.0/gems/audited-4.9.0/lib/audited/sweeper.rb:14:in `around'
 Dec 13 09:15:23 secureframe app/web.1   /app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
 Dec 13 09:15:23 secureframe app/web.1   /app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:139:in `run_callbacks'
 Dec 13 09:15:23 secureframe app/web.1   /app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.2/lib/abstract_controller/callbacks.rb:41:in `process_action'
 Dec 13 09:15:23 secureframe app/web.1   /app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.2/lib/action_controller/metal/rescue.rb:22:in `process_action'
 Dec 13 09:15:23 secureframe app/web.1   /app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.2/lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
 Dec 13 09:15:23 secureframe app/web.1   /app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/notifications.rb:180:in `block in instrument'
 Dec 13 09:15:23 secureframe app/web.1   /app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
 Dec 13 09:15:23 secureframe app/web.1   /app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/notifications.rb:180:in `instrument'
 Dec 13 09:15:23 secureframe app/web.1   /app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.2/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
 Dec 13 09:15:23 secureframe app/web.1   /app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.2/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
 Dec 13 09:15:23 secureframe app/web.1   /app/vendor/bundle/ruby/2.6.0/gems/scout_apm-4.0.0/lib/scout_apm/instruments/action_controller_rails_3_rails4.rb:117:in `process_action'
 Dec 13 09:15:23 secureframe app/web.1   /app/vendor/bundle/ruby/2.6.0/gems/searchkick-4.6.3/lib/searchkick/logging.rb:212:in `process_action'
 Dec 13 09:15:23 secureframe app/web.1   /app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
 Dec 13 09:15:23 secureframe app/web.1   /app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.2/lib/abstract_controller/base.rb:136:in `process'
 Dec 13 09:15:23 secureframe app/web.1   /app/vendor/bundle/ruby/2.6.0/gems/actionview-6.0.3.2/lib/action_view/rendering.rb:39:in `process'
 Dec 13 09:15:23 secureframe app/web.1   /app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.2/lib/action_controller/metal.rb:190:in `dispatch'
 Dec 13 09:15:23 secureframe app/web.1   /app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.2/lib/action_controller/metal.rb:254:in `dispatch'
 Dec 13 09:15:23 secureframe app/web.1   /app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.3.2/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
 ```
 

## Expected behavior

These api requests should succeed as expected with 200 response code.

**Comment by JuanSantamariaCol** [comment]
Hi @kvish , How did you solve de problem?

**Comment by anandbait** [comment]
@kvish @JuanSantamariaCol How did you solve this error?
I am getting this issue while I am exporting PDF using wicked_pdf from rake task
