### ISSUE TITLE
generate devise:install error

### ISSUE THREAD

**Issue by mohamed-bahaa21** [heartcombo/devise#5509]
## Environment

- Ruby **[2.7.5p203 (2021-11-24 revision f69aeb8314) [x64-mingw32]]**
- Rails **[6.1.6.1]**
- Devise **[4.8.1]**

## Current behavior

when running `rails generate devise:install`
```

Traceback (most recent call last):
        28: from bin/rails:4:in `<main>'
        27: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        26: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        25: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/railties-6.1.6.1/lib/rails/commands.rb:18:in `<main>'
        24: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/railties-6.1.6.1/lib/rails/command.rb:48:in `invoke'
        23: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/railties-6.1.6.1/lib/rails/command/base.rb:69:in `perform'
        22: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        21: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        20: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        19: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/railties-6.1.6.1/lib/rails/commands/generate/generate_command.rb:21:in `perform'
        18: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/railties-6.1.6.1/lib/rails/command/actions.rb:14:in `require_application_and_environment!'
        17: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/railties-6.1.6.1/lib/rails/command/actions.rb:22:in `require_application!'
        16: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        15: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        14: from C:/Users/Moham/OneDrive/Desktop/insta-clone/config/application.rb:7:in `<main>'
        13: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler.rb:174:in `require'
        12: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler/runtime.rb:58:in `require'
        11: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler/runtime.rb:58:in `each'
        10: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler/runtime.rb:69:in `block in require'
         9: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler/runtime.rb:69:in `each'
         8: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler/runtime.rb:74:in `block (2 levels) in require'
         7: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
         6: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
         5: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/pg-0.18.4-x64-mingw32/lib/pg.rb:4:in `<main>'
         4: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/activesupport-6.1.6.1/lib/active_support/dependencies.rb:332:in `require'
         3: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/activesupport-6.1.6.1/lib/active_support/dependencies.rb:299:in `load_dependency'
         2: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/activesupport-6.1.6.1/lib/active_support/dependencies.rb:332:in `block in require'
         1: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:15:in `require'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:15:in `require': cannot load such file -- pg_ext (LoadError)
        29: from bin/rails:4:in `<main>'
        28: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        27: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        26: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/railties-6.1.6.1/lib/rails/commands.rb:18:in `<main>'
        25: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/railties-6.1.6.1/lib/rails/command.rb:48:in `invoke'
        24: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/railties-6.1.6.1/lib/rails/command/base.rb:69:in `perform'
        23: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        22: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        21: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        20: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/railties-6.1.6.1/lib/rails/commands/generate/generate_command.rb:21:in `perform'
        19: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/railties-6.1.6.1/lib/rails/command/actions.rb:14:in `require_application_and_environment!'
        18: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/railties-6.1.6.1/lib/rails/command/actions.rb:22:in `require_application!'
        17: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        16: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        15: from C:/Users/Moham/OneDrive/Desktop/insta-clone/config/application.rb:7:in `<main>'
        14: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler.rb:174:in `require'
        13: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler/runtime.rb:58:in `require'
        12: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler/runtime.rb:58:in `each'
        11: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler/runtime.rb:69:in `block in require'
        10: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler/runtime.rb:69:in `each'
         9: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler/runtime.rb:74:in `block (2 levels) in require'
         8: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
         7: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
         6: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/pg-0.18.4-x64-mingw32/lib/pg.rb:3:in `<main>'
         5: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/pg-0.18.4-x64-mingw32/lib/pg.rb:14:in `rescue in <main>'
         4: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/activesupport-6.1.6.1/lib/active_support/dependencies.rb:332:in `require'
         3: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/activesupport-6.1.6.1/lib/active_support/dependencies.rb:299:in `load_dependency'
         2: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/activesupport-6.1.6.1/lib/active_support/dependencies.rb:332:in `block in require'
         1: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:15:in `require'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:15:in `require': cannot load such file -- 2.7/pg_ext (LoadError)
```

**Comment by Mohamed-Elzohary** [comment]
I tried
`bundle install --redownload`
`gem install pg -f`

**Comment by suryanarayanan035** [comment]
Are you using PostgreSQL?
If yes, then you will need **pg** gem to be installed in your rails application as your error says it is unable to load pg_ext which is a makefile generated by pg gem. This pg gem is the database to your PostgreSQL database.
To solve this issue, just run the following command
`bundle add pg`

**Comment by nashby** [comment]
@mohamed-bahaa21 seems like it's indeed related to pg and not devise. You'll have more luck getting the answer on Stackoverflow for such questions. Sorry!
