### ISSUE TITLE
Error during failsafe response: uncaught throw :warden

### ISSUE THREAD

**Issue by raybradley** [heartcombo/devise#5656]
## Environment

- Ruby 3.2.2
- Rails 7.1.2
- Devise 4.9.3

## Current behavior

Seeing `Error during failsafe response: uncaught throw :warden`

```
...
Error during failsafe response: uncaught throw :warden
scoutplan-app-1          |   /usr/local/bundle/gems/warden-1.2.9/lib/warden/proxy.rb:134:in `throw'
scoutplan-app-1          |   /usr/local/bundle/gems/warden-1.2.9/lib/warden/proxy.rb:134:in `authenticate!'
scoutplan-app-1          |   /usr/local/bundle/gems/devise-4.9.3/lib/devise/controllers/helpers.rb:118:in `authenticate_user!'
scoutplan-app-1          |   /usr/local/bundle/gems/activesupport-7.1.2/lib/active_support/callbacks.rb:403:in `block in make_lambda'
scoutplan-app-1          |   /usr/local/bundle/gems/activesupport-7.1.2/lib/active_support/callbacks.rb:202:in `block (2 levels) in halting'
scoutplan-app-1          |   /usr/local/bundle/gems/actionpack-7.1.2/lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
scoutplan-app-1          |   /usr/local/bundle/gems/activesupport-7.1.2/lib/active_support/callbacks.rb:203:in `block in halting'
scoutplan-app-1          |   /usr/local/bundle/gems/activesupport-7.1.2/lib/active_support/callbacks.rb:598:in `block in invoke_before'
scoutplan-app-1          |   /usr/local/bundle/gems/activesupport-7.1.2/lib/active_support/callbacks.rb:598:in `each'
scoutplan-app-1          |   /usr/local/bundle/gems/activesupport-7.1.2/lib/active_support/callbacks.rb:598:in `invoke_before'
scoutplan-app-1          |   /usr/local/bundle/gems/activesupport-7.1.2/lib/active_support/callbacks.rb:119:in `block in run_callbacks'
...
```
## Expected behavior

App ran fine under Rails 7.0.8

**Comment by raybradley** [comment]
User error...sorry for the false alarm.
